const tintColor = '#2f95dc';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  normalText: '#fff',

  grapefruitLight: '#ED5565',
  grapefruitDark: '#DA4453',
  bittersweetLight: '#FC6E51',
  bittersweetDark: '#E9573F',
  sunflowerDark: '#F6BB42',
  sunflowerLight: '#FFCE54',
  sunflowerClear: '#ffe4a1',
  grassLight: '#A0D468',
  grassDark: '#8CC152',
  mintLight: '#48CFAD',
  mintDark: '#37BC9B',
  aquaLight: '#4FC1E9',
  aquaDark: '#3BAFDA',
  bluejeansLight: '#5D9CEC',
  bluejeansDark: '#4A89DC',
  lavanderLight: '#AC92EC',
  lavanderDark: '#967ADC',
  lavanderDarker: '#69559a',
  pinkroseClear: '#fbe7f2',
  pinkroseLight: '#EC87C0',
  pinkroseDark: '#D770AD',
  mediumGrayLight: '#CCD1D9',
  mediumGrayDark: '#AAB2BD',
  darkGrayClear: '#d0d3d6',
  darkGrayLight: '#656D78',
  darkGrayDark: '#434A54',
  actionColor: '#F2FF66',
  neutral100: "#FFFFFF",
  neutral200: "#F4F2F1",
  neutral300: "#D7CEC9",
  displayBlack: "#2F2F2F",
};
